server {
    listen 9000;
    server_name localhost;

    # Define the root directory for the front-end files
    root /var/www/html/softy-pinko-front-end;

    # Define the index file to load
    index index.html;

    # Location block to serve the front-end content
    location / {
        try_files $uri $uri/ =404;
    }
}
