version: "3.8"

services:
  backend:
    build:
      context: ./back-end
    ports:
      - "5252:5252"
    networks:
      - softy-pinko-network

  frontend:
    build:
      context: ./front-end
    ports:
      - "9000:9000"
    depends_on:
      - backend
    networks:
      - softy-pinko-network

networks:
  softy-pinko-network:
    driver: bridge
