# Use the latest Ubuntu image as base
FROM ubuntu:latest

# Update APT and upgrade installed software
RUN apt-get update && apt-get upgrade -y

# Set up the command to echo "Hello, World!" when the container is run
CMD echo "Hello, World!"
